name: mayo_cloud_storage
description: Packake that exposes simple APIs to perform CRUD operations on Cloud Storage
version: 0.0.1
homepage: https://mayosoftware.es

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  firebase_storage: ^10.2.13
  flutter:
    sdk: flutter
  very_good_analysis: ^3.0.1

dev_dependencies:
  firebase_storage_mocks: ^0.5.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter